config/routes.rb
Rails.application.routes.draw do

  resources :projects, only: [:index, :show, :create, :destroy]

  resources :tasks, only: [:create, :destroy] do
    member do
      get :start, :stop, :finish
    end
  end

  root to: 'projects#index'

end

app/models/log.rb
class Log < ActiveRecord::Base

  belongs_to :task

  default_scope { order(:stop) }

  validates_presence_of :task

  def duration
    ((stop? ? stop.to_time : Time.now) - start.to_time).to_i
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks, dependent: :destroy
  has_many :logs, through: :tasks

  validates :name, presence: { message: 'Please provide a name' }

  def logged
    logs.map(&:duration).sum
  end

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  has_many :logs, dependent: :destroy

  validates :name, presence: { message: 'Please provide a name' }
  validates_presence_of :project

  def work?
    !logs.empty? && !logs.first.stop
  end

  def logged
    logs.map(&:duration).sum
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
    @project = Project.includes(tasks: :logs).first
    @project ||= Project.create(name: 'Demo Project')
  end

  def show
    @project = Project.includes(tasks: :logs).find(params[:id])
  end

  def create
    @project = Project.create(name: params[:name])
    @projects = Project.all
  end

  def destroy
    @deleted = Project.find(params[:id]).destroy
    @project = Project.includes(tasks: :logs).first
    render :show
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @task = Project.find(params[:project_id]).tasks.create(name: params[:name])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
  end

  def finish
    @task = Task.find(params[:id])
    @task.update(done: true)
    render :refresh
  end

  def start
    @task = Task.find(params[:id])
    @log = Log.create(task: @task, start: Time.now)
    render :refresh
  end

  def stop
    @task = Task.find(params[:id])
    @log = @task.logs.first.update(stop: Time.now)
    render :refresh
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper

  def format_logged(total)
    format("%02d:%02d:%02d", total/(60 * 60), (total/60) % 60, total % 60)
  end

end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Trackapp
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    = yield

app/views/logs/_log.html.slim
div[class="log#{' log-work' if !log.stop?}"]

  span.log-summary #{format_logged(log.duration)}

  span #{l(log.start, format: :long)} 

  - if log.stop
    span &#8611; #{l(log.stop, format: :long)}

app/views/projects/_project.html.slim
= link_to project.name, project_path(project), {class: "project project-#{project.id}", remote: true}

app/views/projects/index.html.slim
ul.tabs
  li
    = form_tag('/projects', method: :post, remote: true) do
      = text_field_tag(:name, nil, placeholder: 'New project')
  - @projects.each_with_index do |project, index|
    li[class="#{'active' if index == 0}#{' last' if index == @projects.size-1}"]
      = render project 

.project-time= format_logged(@project.logged)

= link_to 'delete project', projects_path(id: @project.id, format: 'js'), { class: 'project-delete', remote: true, method: :delete }

.task-create
  = form_tag('/tasks', method: :post, remote: true) do
    = text_field_tag(:name, nil, placeholder: 'New task')
    = hidden_field_tag(:project_id, "#{@projects.empty? ? 0 : @projects.first.id}")

.taskpane
  = render @project.tasks

app/views/tasks/_task.html.slim
div[class="task task-#{task.id} #{'task-work' if task.work?} #{'task-done' if task.done?}"]

  .time #{format_logged(task.logged)}

  - if task.work?
    = link_to 'stop', stop_task_path(task), { class: 'task-action action-stop', remote: true }

  - if task.done?
    = link_to 'delete', task, { class: 'task-action action-delete', remote: true, method: :delete }

  - if !task.done? && !task.work?
    = link_to 'start', start_task_path(task), { class: 'task-action action-start', remote: true }

    = link_to 'done', finish_task_path(task), { class: 'task-action action-done', remote: true }

  .task-title
    - if task.work?
      span.icon &#9874;
    - elsif task.done?
      span.icon &#10003;
    - else
      span.icon &#9417;
    span #{task.name}
    - if !task.logs.empty?
      span.show-logs  &#8609;

  div[class="task-logs logs-#{task.id}"]
    = render task.logs